version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ecf
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      runas: root